### ISSUE TITLE
Swap file is not created

### ISSUE THREAD

**Issue by rastaman** [fupelaqu/ansible-oraclexe#2]
Hi, 
I use your playbook to install Oracle Express on a vagrant/virtual box virtual machine and the swap file is not created. I have to change the following line in tasks/main.yml :

```
when: (docker == 'no' ) and (not oracle.stat.exists) and (not swap.stat.exists)
```

by this one :

```
when: (not docker) and (not oracle.stat.exists) and (not swap.stat.exists)
```

for the swap file to be created (notice the test on the docker variable).

My ansible version is :

```
$ ansible --version
ansible 1.9.0.1
  configured module search path = None
```

Did there is a problem with the way i use this role or is there an error ?
Best regards,

**Comment by fupelaqu** [comment]
I just added a fix for this issue

**Comment by fupelaqu** [comment]
Hi

I just added a fix for this issue.

Br

**Comment by rastaman** [comment]
Hi, sorry to not have seen it before, but there is 2 other tests in oracle-xe-configure which use an expression which probably didn't work:
$ grep "docker" roles/oraclexe/tasks/oracle-xe-configure.yml 
    when: (not docker) and ansible_os_family == "RedHat"
    when: (not docker) and ansible_os_family == "RedHat"
Best regards and thanks for your time.

**Comment by fupelaqu** [comment]
I just fixed those conditional tests on docker too.
Thanks for your feedback
